### ISSUE TITLE
Unable to run commands

### ISSUE THREAD

**Issue by Firav** [M0diis/M0-CoreCord#2]
**Describe the bug**
Attempt to issue lookup command, such as "co!lookup u:Firav t:10m", receive error.

**To Reproduce**
1. Run plugin
2. Attempt lookup command on Discord
3. Receive sadness

**Expected behavior**
Output of CO log lookup.

**Screenshots**
`[02:35:49 ERROR]: [net.dv8tion.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.StringLatin1.charAt(StringLatin1.java:48) ~[?:?]
        at java.lang.String.charAt(String.java:711) ~[?:?]
        at me.m0dii.CoreCord.CoSQL.lookUpData(CoSQL.java:252) ~[?:?]
        at me.m0dii.CoreCord.Listeners.DiscordListener.onMessageReceived(DiscordListener.java:235) ~[?:?]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:431) ~[?:?]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[?:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[?:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[?:?]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]`

**Environment:**
 - OS: debian
 - Server version: Paper 1.16.5 (git-Paper-783)
 - Java version 16.0.1
 - Plugin version 1.7.1

**Comment by M0diis** [comment]
Hey.

Thanks for noticing the issue.
I have fixed this in the latest release ([1.7.2](https://github.com/M0diis/M0-CoreCord/releases/tag/1.7.2)).

**Comment by Firav** [comment]
Tested and working in live environment. Thanks!

**Comment by M0diis** [comment]
No problem.
Glad the issue is resolved.

**Comment by Firav** [comment]
Still having some issues with this.

`[17:33:45 ERROR]: [net.dv8tion.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.StringIndexOutOfBoundsException: index -1, length 0
        at java.lang.String.checkIndex(String.java:3710) ~[?:?]
        at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:970) ~[?:?]
        at java.lang.StringBuilder.deleteCharAt(StringBuilder.java:294) ~[?:?]
        at me.m0dii.corecord.CoSQL.lookUpData(CoSQL.java:258) ~[?:?]
        at me.m0dii.corecord.listeners.DiscordListener.onMessageReceived(DiscordListener.java:235) ~[?:?]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:431) ~[?:?]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[?:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[?:?]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[?:?]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149) ~[?:?]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122) ~[?:?]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[?:?]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:990) ~[?:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]`
        
When issuing command co!lookup u:Combie720 t:24h

**Comment by M0diis** [comment]
Does such user exist?

**Comment by Firav** [comment]
The user has joined the server, but may not have a record within the database.

Would you be able to add a error response for no user found? Like the no results found error that already exists.

**Comment by M0diis** [comment]
I've updated the uploaded artifact with the same version, hopefully that fixes the issue.

**Comment by Firav** [comment]
Okay, so the latest 1.7.2 file is the one Im looking for?

**Comment by M0diis** [comment]
Yeah.

I just changed the artifact in the release.

**Comment by Firav** [comment]
Just tested latest artifact, returns a user error perfectly. Thank you!

**Comment by M0diis** [comment]
Alright.
Glad it has been resolved.
Enjoy the plugin.
